### ISSUE TITLE
组件prop存在缓存

### ISSUE THREAD

**Issue by jackie-su** [RickyHeaven/ar-cascader#1]
无论是使用value传入，还是v-model绑定，当把这个prop清空后，组件内的值还是未能自动清除，除非用v-if刷新组件。
![C359A81D-5526-4e11-AD68-5A92840C19BA](https://github.com/RickyHeaven/ar-cascader/assets/49759189/752b53dd-57bb-4729-94d3-0e16ddd6dfcf)

**Comment by RickyHeaven** [comment]
1.0.10及更低的版本确实存在一些问题，重构的全新版本已经上线，使用了最新的来自国家统计局的数据，更新了一些很棒的功能，如名字name模糊查询快速定位到你要找的地点选项，欢迎使用。
